# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('ID_DetalleMedicamento', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('ID_Cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cita.cita', verbose_name='Cita No')),
                ('ID_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamento.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Detalle Medicamento',
            },
        ),
    ]
