# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('ID_TipoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_TipoMascota', models.CharField(max_length=10, unique=True, verbose_name='Codigo de tipo mascota')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Tipo de mascota',
            },
        ),
    ]
