# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_de_cita', '0001_initial'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('ID_Cita', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Cita', models.CharField(max_length=10, unique=True, verbose_name='Cita')),
                ('Fecha_Realizacion', models.DateField(verbose_name='Fecha de realizacion')),
                ('Fecha_de_Cita', models.DateField(verbose_name='Fecha de cita')),
                ('Peso', models.CharField(max_length=30, verbose_name='Peso')),
                ('ID_EstadoCita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado_de_cita.estadodecita', verbose_name='Estado de la cita')),
                ('ID_Mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascota.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Cita',
            },
        ),
    ]
