# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Venta', models.CharField(max_length=10, unique=True, verbose_name='Codigo de venta')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('ID_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Nombre del cliente')),
            ],
            options={
                'verbose_name': 'Venta',
            },
        ),
    ]
