# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('ID_DetalleCompra', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('ID_Compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compra', verbose_name='Compra')),
                ('ID_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamento.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Detalles de Compra',
            },
        ),
    ]
