CATALOGOS_SETTING_APP = ['apps.catalogos.cita',
                         'apps.catalogos.detalle_cita',
                         'apps.catalogos.detalle_medicamento',
                         'apps.catalogos.enfermedades',
                         'apps.catalogos.estado_de_cita',
                         'apps.catalogos.mascota',
                         'apps.catalogos.medicamento',
                         'apps.catalogos.presentacion',
                         'apps.catalogos.raza',
                         'apps.catalogos.tipo_mascota',
                         'apps.catalogos.unidad_medida']