# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('ID_Unidad_Medida', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Unidad_Medida', models.CharField(max_length=10, unique=True, verbose_name='Codigo de unidad medida')),
                ('Descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Unidades de Medida',
            },
        ),
    ]
