# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Compra', models.CharField(max_length=10, unique=True, verbose_name='Codigo de compra')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Compras',
            },
        ),
    ]
