# Generated by Django 4.2 on 2024-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadodeCita',
            fields=[
                ('ID_EstadoCita', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_EstadoCita', models.CharField(max_length=10, unique=True, verbose_name='Codigo de estado de cita')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estados de cita',
            },
        ),
    ]
